<?php

return [
    'motivational' => [
        ['text' => 'Life is 10% what happens to you and 90% how you react to it.',
            'author' => 'Charles R. Swindoll',
        ],
        ['text' => 'Failure will never overtake me if my determination to succeed is strong enough.',
            'author' => 'Og Mandino',
        ],
        ['text' => 'Arriving at one goal is the starting point to another',
            'author' => 'John Dewey',
        ],
        ['text' => 'In order to succeed, we must first believe we can.',
            'author' => 'Nikos Kazantzakis',
        ],
        ['text' => 'What you do today can improve all your tomorrows.',
            'author' => 'Ralph Marston',
        ],
        ['text' => 'Don\'t watch the clock; do what it does. Keep going.',
            'author' => 'Sam Levenson',
        ],
        ['text' => 'A creative man is motivated by desire to achieve, not by desire to beat others.',
            'author' => 'Ayn Rand',
        ],
        ['text' => 'It does not matter how slowly you go as long as you don\'t stop.',
            'author' => 'Confucius',
        ],
        ['text' => 'If you can dream it, you can do it.',
            'author' => 'Walt Disney',
        ],
        ['text' => 'Keep yout eyes on the stars and your feet on the ground.',
            'author' => 'Theodore Roosevelt',
        ],
        ['text' => 'You are never too old to set another goal or to dream a new dream.',
            'author' => 'C.S. Lewis',
        ],
        ['text' => 'The secret of getting ahead is getting started.',
            'author' => 'Mark Twain',
        ],
        ['text' => 'Always do your best. What you plant now, you will harvest later.',
            'author' => 'Og Mandino',
        ],
        ['text' => 'Accept the challenges so that you can feel the exhilaration of victory.',
            'author' => 'George S. Patton',
        ],
        ['text' => 'With the new day comes new strength and new thoughts.',
            'author' => 'Eleanor Roosevelt',
        ],
        ['text' => 'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.',
            'author' => 'Thomas A. Edison',
        ],
        ['text' => 'Knowing is not enough; we must apply. Willing is not enough; we must do.',
            'author' => 'Johann Wolfgang von Goethe',
        ],
        ['text' => 'Aim for the moon. If you miss, you may hit a star.',
            'author' => 'W. Clement Stone',
        ],
        ['text' => 'Start where you are. Use what you have. Do what you can.',
            'author' => 'Arthur Ashe',
        ],
        ['text' => 'Problems are not stop signs, they are guidelines',
            'author' => 'Robert H. Schuller',
        ],
        ['text' => 'Good, better, best. Never let it rest.\'Til your good is better and your better is best.',
            'author' => 'St. Jerome',
        ],
        ['text' => 'Never complain and never explain.',
            'author' => 'Benjamin Disraeli',
        ],
        ['text' => 'The right man in the wrong place can make all the difference in the world.',
            'author' => 'G-Man',
        ],
        ['text' => 'We all make choices in life, but in the end our choices make us.',
            'author' => 'Andrew Ryan',
        ],
        ['text' => 'A man chooses. A slave obeys.',
            'author' => 'Andrew Ryan',
        ],
        ['text' => 'Death is inevitable. Our fear of it makes us play safe, blocks out emotion. It\'s a losing game. Without passion you are already dead.',
            'author' => 'Max Payne',
        ],
        ['text' => 'Stand in the ashes of a trillion dead souls and ask the ghosts if honor matters. Their silence is your answer.',
            'author' => 'Javik',
        ],
        ['text' => 'Whenever there is a meeting, a parting is sure to follow. However, that parting need not last forever. Whether a parting be forever or merely for a short time. That is up to you.',
            'author' => 'Happy Mask Salesman',
        ],
        ['text' => 'Good men mean well. We just don\'t always end up doing well.',
            'author' => 'Isaac Clarke',
        ],
        ['text' => 'The best solution to a problem is usually the easiest one.',
            'author' => 'GLaDOS',
        ],
        ['text' => 'What is better - to be born good, or to overcome your evil nature through great effort?',
            'author' => 'Paarthunax',
        ],
        ['text' => 'Hard to see the big picture behind a pile of corpses.',
            'author' => 'Mordin Solus',
        ],
    ],
];